In [6]:
l = [5, 2, 7, 6, 3, 1, 9]
su=0
maxi = max(l)

mini = min(l)

for i in l :
    n =  (i - mini)/(maxi-mini)
    print(n)

0.5
0.125
0.75
0.625
0.25
0.0
1.0


In [7]:
for i in l:
    su=su+int(i)
mean=su/len(l)
print(mean)

4.714285714285714


In [8]:
def stand(l):
    var=0
    for i in range(len(l)):
        var+=(l[i]-mean)**2
    var=var/len(l)
    import math
    std=math.sqrt(var)
    for i in range(len(l)):
        l[i]=(l[i]-mean)/std
    return l
print (stand(l))
        

[0.10752066611409403, -1.0214463280838937, 0.8601653289127525, 0.4838429975134233, -0.6451239966845644, -1.397768659483223, 1.612809991711411]


In [4]:
import pandas as pd
import numpy as np
data=pd.read_csv("samp.csv")
data
import math 
cluster1=[]
cluster2=[]
cluster3=[]
cl1=[6.2,3.2]
cl2=[6.6,3.7]
cl3=[6.5,3.0]
def euc(a,b):
    d1=math.sqrt((cl1[0]-a)**2 + (cl1[1]-b)**2)
    d2=math.sqrt((cl2[0]-a)**2 + (cl2[1]-b)**2)
    d3=math.sqrt((cl3[0]-a)**2 + (cl3[1]-b)**2)
    md=min(d1,d2,d3)
    if(md==d1):
        cluster1.append([a,b])
    elif(md==d2):
        cluster2.append([a,b])
    else:
        cluster3.append([a,b])

    

In [5]:
for i in range(0,10):
    euc(data['x1'][i],data['x2'][i])
print("cluster1 : ",cluster1)
print("cluster2 : ",cluster2)
print("cluster3 : ",cluster3)

cluster1 :  [[5.9, 3.2], [4.6, 2.9], [4.7, 3.2], [5.0, 3.0], [4.9, 3.1], [5.1, 3.8], [6.0, 3.0]]
cluster2 :  [[5.5, 4.2]]
cluster3 :  [[6.2, 2.8], [6.7, 3.1]]


In [9]:
from copy import deepcopy


def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)
def main():
    k = 3
    X = pd.read_csv('samp.csv',index_col=False)
    print(X,"\n")

    x1 = X['x1'].values
    x2 = X['x2'].values
    X = np.array(list(zip(x1, x2)))
    print(X,"\n")
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape,"\n")

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old,"\n")
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(X))
    print(clusters,"\n")
    error = euclidean(Centroid, Centroid_old, None)
    print(error,"\n")
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(X)):
            #print(X[i])
            distances = euclidean(X[i], Centroid)
            #print(distances)
            cluster = np.argmin(distances)
            clusters[i] = cluster

            print(clusters)
        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid,"\n")
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error,"\n")  
    

if __name__ == "__main__": 
    main()

    x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0 

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]] 

Initial Centroids
(3, 2) 

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

12.537144692236463 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[0. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
 Centre of the clusters after  1  Iteration 
 [[5.1714287 3.1714287]
 [5.5       4.2      ]
 [6.45      2.95     ]] 

Error  ...  1.5886393 

[2. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[2. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[2. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[2. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[2. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
[2. 0. 2. 0. 1. 0. 